#!/bin/sh
#
# An example hook script to verify what is about to be committed
# by applypatch from an e-mail message.
#
# The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-applypatch".

"C:/Program Files/MySQl/MySQL Server 5.6/bin/mysqldump" -u Sopata --password='goshko' ff1 > "C:/Users/I312038/hdbstudio/FinalFantasy1JS/ff1.sql" 
